services:
  postgres:
    image: postgres:16.9-alpine3.20
    container_name: music-online_postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: the_muse_db
    ports:
      - "5432:5432"
